name: Biotech Daily Digest

on:
  schedule:
    - cron: "30 14 * * *"   # 07:30 America/Los_Angeles
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate digest
        run: python scripts/biotech_digest.py

      - name: Commit digest
        run: |
          git config user.name "biotech-digest-bot"
          git config user.email "actions@users.noreply.github.com"
          git add digest/*.md README.md data/seen.json
          git commit -m "chore(digest): update $(date -u +'%Y-%m-%d')" || echo "No changes to commit"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Schedule Commits
        run: |
          for i in {1..3}; do
            echo "heartbeat $i $(date -u)" >> data/heartbeat.log
            git add data/heartbeat.log
            git commit -m "chore: heartbeat $i"
            sleep 10
          done
        if: always()
