name: Biotech Daily Digest

permissions:
  contents: write

on:
  schedule:
    - cron: "30 14 * * *"   # 07:30 America/Los_Angeles
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate digest
        run: python scripts/biotech_digest.py

      - name: Update homepage to today
        run: |
          TODAY="$(date -u +'%Y-%m-%d')"
          cat > index.md <<EOF
          # Biotech Daily Digest

          - Latest: [${TODAY} Digest](digest/${TODAY}.md)
          - [Archive](archive.md)

          All digests live in \`digest/\`. Bookmark this page to get the newest link every morning.
          EOF

      - name: Build archive page
        run: |
          echo "# Archive" > archive.md
          echo "" >> archive.md
          ls -1 digest/*.md 2>/dev/null | sort -r | while read f; do
            base="$(basename "$f")"
            echo "- [${base%.md}](digest/${base})" >> archive.md
          done || true

      - name: Configure git author
        run: |
          git config user.name "Himay Makhija"
          git config user.email "68885248+mknoir@users.noreply.github.com"
          echo "GIT_COMMITTER_NAME=Himay Makhija" >> $GITHUB_ENV
          echo "GIT_COMMITTER_EMAIL=68885248+mknoir@users.noreply.github.com" >> $GITHUB_ENV

      - name: Commit digest
        run: |
          git add digest/*.md README.md data/seen.json index.md archive.md _config.yml
          if ! git diff --cached --quiet; then
            git commit -m "chore(digest): update $(date -u +'%Y-%m-%d')"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:main

